plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.autobrush31'
    compileSdk 35
    defaultConfig {
        applicationId 'com.example.autobrush31'
        minSdk 30
        targetSdk 35
        versionCode 12
        versionName '1.2'
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.0'
}
