package com.example.autobrush31;

import android.accessibilityservice.AccessibilityService;
import android.accessibilityservice.AccessibilityServiceInfo;
import android.accessibilityservice.GestureDescription;
import android.graphics.Bitmap;
import android.graphics.Path;
import android.os.Build;
import android.os.Handler;
import android.os.Looper;
import android.util.DisplayMetrics;
import android.view.WindowManager;
import android.view.accessibility.AccessibilityEvent;
import android.view.accessibility.AccessibilityNodeInfo;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions;
import com.google.mlkit.vision.text.Text;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executor;

public class AutoBrushAccessibilityService extends AccessibilityService {
 public static volatile AutoBrushAccessibilityService instance;public static volatile String status="服务未连接";private final Handler handler=new Handler(Looper.getMainLooper());private volatile boolean running;private volatile String foregroundPackage="";private int phase;private long phaseAt,lastShotAt,lastOcrAt,lastMoveAt;private int lastPlayerX=-1,lastPlayerY=-1,stuckFrames=0,lastMoveDx=0,lastMoveDy=0;private boolean ocrBusy=false,selected31=false;private static final String GAME=AutoConfig.GAME_PACKAGE;
 @Override public void onServiceConnected(){super.onServiceConnected();instance=this;AccessibilityServiceInfo i=getServiceInfo();if(i!=null){i.flags|=AccessibilityServiceInfo.FLAG_RETRIEVE_INTERACTIVE_WINDOWS;setServiceInfo(i);}status="无障碍已连接";}
 @Override public void onAccessibilityEvent(AccessibilityEvent e){if(e!=null&&e.getPackageName()!=null)foregroundPackage=e.getPackageName().toString();}
 @Override public void onInterrupt(){stopBrush();}@Override public void onDestroy(){stopBrush();if(instance==this)instance=null;super.onDestroy();}
 public boolean startBrush(){if(running){if(!DebugOverlay.show(this))status="正在运行，但悬浮窗未授权";else{status="正在运行，重新连接寻路诊断…";lastShotAt=0;DebugOverlay.reset();}return true;}if(Build.VERSION.SDK_INT<30){status="Android 11及以上才支持截图";return false;}running=true;phase=0;lastShotAt=0;lastOcrAt=0;lastMoveAt=0;lastPlayerX=-1;lastPlayerY=-1;stuckFrames=0;lastMoveDx=0;lastMoveDy=0;ocrBusy=false;selected31=false;phaseAt=System.currentTimeMillis();status="正在确认《迷雾大陆》前台…";if(!DebugOverlay.show(this))status="正在运行（未授权悬浮窗，无法显示寻路调试）";else DebugOverlay.reset();handler.post(loop);return true;}
 public void stopBrush(){running=false;handler.removeCallbacksAndMessages(null);DebugOverlay.hide();status="已停止";}
 public void requestReplan(){lastMoveDx=0;lastMoveDy=0;stuckFrames=0;lastPlayerX=-1;lastPlayerY=-1;lastMoveAt=0;status="已请求重新规划，重新分析小地图…";}
 public boolean isRunning(){return running;}
 private boolean isGameForeground(){if(GAME.equals(foregroundPackage))return true;try{List<android.view.accessibility.AccessibilityWindowInfo> ws=getWindows();if(ws!=null)for(android.view.accessibility.AccessibilityWindowInfo win:ws){if(win==null)continue;AccessibilityNodeInfo root=win.getRoot();if(root!=null){CharSequence p=root.getPackageName();if(p!=null&&GAME.equals(p.toString())){foregroundPackage=GAME;return true;}}}}catch(Throwable ignored){}try{AccessibilityNodeInfo root=getRootInActiveWindow();if(root!=null){CharSequence p=root.getPackageName();if(p!=null){foregroundPackage=p.toString();return GAME.equals(foregroundPackage);}}}catch(Throwable ignored){}return false;}
 private final Runnable loop=new Runnable(){@Override public void run(){if(!running)return;long now=System.currentTimeMillis();if(!isGameForeground()){status="等待《迷雾大陆》进入前台…";handler.postDelayed(loop,500);return;}if(phase==0){status="进入源初秘境";tap(AutoConfig.SECRET_X,AutoConfig.SECRET_Y);phase=1;phaseAt=now;lastOcrAt=0;}else if(phase==1&&now-phaseAt>900){if(!ocrBusy&&now-lastOcrAt>700){lastOcrAt=now;status="正在OCR识别秘境列表，寻找‘地狱31’…";shotForOcr();}if(now-phaseAt>15000&&!selected31){status="仍未识别到‘地狱31’，暂停点击，避免误选地狱33";phaseAt=now-10000;}}else if(phase==2&&now-phaseAt>1800){status="准备进入已识别的地狱31";tap(AutoConfig.ENTER_X,AutoConfig.ENTER_Y);phase=3;phaseAt=now;lastShotAt=0;}else if(phase==3&&now-phaseAt>2200&&now-lastShotAt>500){shot();lastShotAt=now;}handler.postDelayed(loop,phase==3?180:220);}};
 private void shotForOcr(){ocrBusy=true;try{Executor ex=c->handler.post(c);takeScreenshot(0,ex,new TakeScreenshotCallback(){public void onSuccess(ScreenshotResult r){Bitmap b=null;try{Bitmap hw=Bitmap.wrapHardwareBuffer(r.getHardwareBuffer(),r.getColorSpace());if(hw!=null)b=hw.copy(Bitmap.Config.ARGB_8888,false);}catch(Throwable ignored){}finally{if(r.getHardwareBuffer()!=null)r.getHardwareBuffer().close();}if(b!=null)recognize31(b);else ocrBusy=false;}public void onFailure(int e){ocrBusy=false;status="OCR截图失败，继续扫描";}});}catch(Throwable t){ocrBusy=false;status="OCR截图调用失败，继续扫描";}}
 private void recognize31(Bitmap b){try{InputImage image=InputImage.fromBitmap(b,0);TextRecognition.getClient(new ChineseTextRecognizerOptions.Builder().build()).process(image).addOnSuccessListener(text->{try{if(!running||phase!=1)return;android.graphics.Rect hit=find31Rect(text);if(hit!=null){status="OCR确认‘地狱31’，点击实际文字位置";tapScreenshotPoint(hit.centerX(),hit.centerY(),b.getWidth(),b.getHeight());selected31=true;phase=2;phaseAt=System.currentTimeMillis();}else status="OCR未发现‘地狱31’，继续扫描，不误选33";}finally{ocrBusy=false;b.recycle();}}).addOnFailureListener(e->{ocrBusy=false;b.recycle();status="OCR识别失败，继续扫描";});}catch(Throwable t){ocrBusy=false;b.recycle();status="OCR初始化失败，继续扫描";}}
 private String norm(String s){if(s==null)return"";return s.replaceAll("[\\s\\u00A0\\u3000]","").replace("O","0").replace("o","0").replace("I","1").replace("l","1").replace("L","1");}
 private android.graphics.Rect find31Rect(Text text){if(text==null)return null;List<Text.Line> lines=new ArrayList<>();for(Text.TextBlock b:text.getTextBlocks())lines.addAll(b.getLines());for(Text.Line line:lines){String s=norm(line.getText());if(s.contains("地狱31")||s.matches(".*地狱.*31.*"))return new android.graphics.Rect(line.getBoundingBox());}for(Text.Line a:lines){String sa=norm(a.getText());if(!sa.contains("地狱"))continue;android.graphics.Rect ra=a.getBoundingBox();if(ra==null)continue;for(Text.Line c:lines){if(c==a)continue;String sc=norm(c.getText());if(!sc.matches(".*31.*"))continue;android.graphics.Rect rc=c.getBoundingBox();if(rc==null)continue;int gap=Math.max(0,Math.max(ra.top,rc.top)-Math.min(ra.bottom,rc.bottom));int cy=Math.abs(ra.centerY()-rc.centerY());int dx=Math.abs(ra.centerX()-rc.centerX());if((gap<=90||cy<=100)&&dx<=500)return new android.graphics.Rect(Math.min(ra.left,rc.left),Math.min(ra.top,rc.top),Math.max(ra.right,rc.right),Math.max(ra.bottom,rc.bottom));}}return null;}
 private void shot(){status="截图请求中…";try{Executor ex=c->handler.post(c);takeScreenshot(0,ex,new TakeScreenshotCallback(){public void onSuccess(ScreenshotResult r){Bitmap b=null;try{Bitmap hw=Bitmap.wrapHardwareBuffer(r.getHardwareBuffer(),r.getColorSpace());if(hw!=null)b=hw.copy(Bitmap.Config.ARGB_8888,false);if(b!=null){status="截图成功 "+b.getWidth()+"×"+b.getHeight();frame(b);}}catch(Throwable t){status="截图处理失败："+t.getClass().getSimpleName();}finally{if(r.getHardwareBuffer()!=null)r.getHardwareBuffer().close();}if(b==null)DebugOverlay.update(null,null,status);}public void onFailure(int e){status="截图失败 code="+e;DebugOverlay.update(null,null,status);}});}catch(Throwable t){status="截图调用失败："+t.getClass().getSimpleName();DebugOverlay.update(null,null,status);}}
 private void publishDebug(Bitmap m,MapNavigatorV2.Result q,String st){DebugOverlay.update(m,q,st);}
 private void frame(Bitmap f){if(f==null||f.isRecycled())return;int w=f.getWidth(),h=f.getHeight();try{int l=sx(AutoConfig.MAP_L,w),t=sy(AutoConfig.MAP_T,h),r=sx(AutoConfig.MAP_R,w),b=sy(AutoConfig.MAP_B,h);l=Math.max(0,Math.min(l,w-1));r=Math.max(l+1,Math.min(r,w));t=Math.max(0,Math.min(t,h-1));b=Math.max(t+1,Math.min(b,h));Bitmap m=Bitmap.createBitmap(f,l,t,r-l,b-t);MapNavigatorV2.Result q=MapNavigatorV2.analyze(m,lastMoveDx,lastMoveDy);if(!q.foundPlayer){status="截图成功，人物未找到（看诊断中的绿像素和原图）";publishDebug(m,q,status);m.recycle();return;}if(q.confidence<0.25f){status="截图成功，人物候选较弱，但继续显示诊断，不再卡死";}else status="截图成功，人物已定位";if(lastPlayerX>=0){int dd=Math.abs(q.playerX-lastPlayerX)+Math.abs(q.playerY-lastPlayerY);if(dd<=1)stuckFrames++;else stuckFrames=Math.max(0,stuckFrames-3);}lastPlayerX=q.playerX;lastPlayerY=q.playerY;if(!q.roadDirection){status="截图成功，人物已找到，但没有确认道路；请反馈悬浮窗诊断";publishDebug(m,q,status);m.recycle();return;}int dx=q.dx,dy=q.dy;if(dx==0&&dy==0){status="截图成功，方向为空；请反馈诊断";publishDebug(m,q,status);m.recycle();return;}long since=System.currentTimeMillis()-lastMoveAt;long hold=stuckFrames>=3?850:700;status="截图成功，小地图确认道路，移动："+(dx>0?"右":"")+(dx<0?"左":"")+(dy<0?"上":"")+(dy>0?"下":"")+"，"+hold+"ms";if(since>350){move(dx,dy,hold);lastMoveAt=System.currentTimeMillis();lastMoveDx=dx;lastMoveDy=dy;}publishDebug(m,q,status);m.recycle();}finally{f.recycle();}}
 private DisplayMetrics dm(){DisplayMetrics d=new DisplayMetrics();try{WindowManager w=(WindowManager)getSystemService(WINDOW_SERVICE);if(w!=null)w.getDefaultDisplay().getRealMetrics(d);}catch(Throwable ignored){}return d.widthPixels>0?d:getResources().getDisplayMetrics();}
 private int sx(int x,int w){return Math.round(x*w/(float)AutoConfig.REF_W);}private int sy(int y,int h){return Math.round(y*h/(float)AutoConfig.REF_H);}
 private void tap(int x,int y){if(!isGameForeground())return;DisplayMetrics d=dm();tapRaw(sx(x,d.widthPixels),sy(y,d.heightPixels));}
 private void tapRaw(int x,int y){Path p=new Path();p.moveTo(x,y);dispatchGesture(new GestureDescription.Builder().addStroke(new GestureDescription.StrokeDescription(p,0,100)).build(),null,null);}
 private void tapScreenshotPoint(int x,int y,int shotW,int shotH){if(!isGameForeground())return;DisplayMetrics d=dm();tapRaw(Math.round(x*d.widthPixels/(float)Math.max(1,shotW)),Math.round(y*d.heightPixels/(float)Math.max(1,shotH)));}
 private void move(int x,int y,long ms){if(!isGameForeground()||(x==0&&y==0))return;DisplayMetrics d=dm();int a=sx(AutoConfig.JOY_X,d.widthPixels),b=sy(AutoConfig.JOY_Y,d.heightPixels);float z=(float)Math.sqrt(x*x+y*y),radius=118f*d.widthPixels/AutoConfig.REF_W;Path p=new Path();p.moveTo(a,b);p.lineTo(Math.round(a+radius*x/z),Math.round(b+radius*y/z));dispatchGesture(new GestureDescription.Builder().addStroke(new GestureDescription.StrokeDescription(p,0,ms)).build(),null,null);}
}
