package com.example.autobrush31;

import android.graphics.Bitmap;
import android.graphics.Color;
import java.util.ArrayDeque;

/** Diagnostic-first minimap analyzer. */
public final class MapNavigatorV2 {
 private MapNavigatorV2(){}
 public static final class Result { public boolean foundPlayer,roadDirection; public int dx,dy,playerX=-1,playerY=-1,targetX=-1,targetY=-1,pathLength,routeCells; public float confidence,roadPct,fogPct,nonRoadPct; public String debug=""; }
 public static Result analyze(Bitmap s,int prevDx,int prevDy){ Result o=new Result(); if(s==null||s.isRecycled()){o.debug="MAP=NULL：没有收到小地图Bitmap";return o;} int w=s.getWidth(),h=s.getHeight(); Stats st=stats(s);o.roadPct=st.road;o.fogPct=st.fog;o.nonRoadPct=Math.max(0,1-o.roadPct-o.fogPct); int[] p=findPlayer(s,w,h); if(p[0]<0){o.debug="截图正常 " + w+"x"+h+" | 绿色像素="+st.green+" | 未找到人物 | 道路="+pct(o.roadPct)+" 雾="+pct(o.fogPct)+" 非道路="+pct(o.nonRoadPct);return o;} o.foundPlayer=true;o.playerX=p[0];o.playerY=p[1];o.confidence=Math.min(1f,p[2]/45f); int cell=Math.max(2,Math.min(4,Math.min(w,h)/55)); int[][] ds={{1,0},{1,1},{0,1},{-1,1},{-1,0},{-1,-1},{0,-1},{1,-1}}; double best=-1e9;int bdX=0,bdY=0,bl=0;StringBuilder d=new StringBuilder(); for(int[] q:ds){int a=cont(s,p[0],p[1],q[0],q[1],cell,false),b=cont(s,p[0],p[1],q[0],q[1],cell,true),c=wide(s,p[0],p[1],q[0],q[1],cell);d.append(name(q[0],q[1])).append('=').append(a).append('/').append(b).append('/').append(c).append(' ');if(a<2&&b<3)continue;double score=Math.max(a*32,b*25)+c*8;if(prevDx!=0||prevDy!=0){int dot=q[0]*prevDx+q[1]*prevDy;if(dot>0)score+=130;if(dot<0)score-=320;}if(q[0]!=0&&q[1]!=0)score-=10;if(score>best){best=score;bdX=q[0];bdY=q[1];bl=Math.max(a,Math.min(9,b));}} if(bl>=2){o.dx=bdX;o.dy=bdY;o.roadDirection=true;o.pathLength=bl;o.routeCells=bl;o.targetX=p[0]+bdX*bl*cell;o.targetY=p[1]+bdY*bl*cell;}o.debug="截图正常 "+w+"x"+h+" | 绿色像素="+st.green+" | 人物("+o.playerX+","+o.playerY+") | 道路="+pct(o.roadPct)+" 雾="+pct(o.fogPct)+" 非道路="+pct(o.nonRoadPct)+" | "+d+(o.roadDirection?"=>"+name(o.dx,o.dy):"=>无连续道路");return o; }
 private static class Stats{float road,fog;int green;}
 private static Stats stats(Bitmap s){Stats z=new Stats();int total=0,rr=0,ff=0;for(int y=0;y<s.getHeight();y+=2)for(int x=0;x<s.getWidth();x+=2){int c=s.getPixel(x,y),r=Color.red(c),g=Color.green(c),b=Color.blue(c);int lum=(299*r+587*g+114*b)/1000,sp=Math.max(r,Math.max(g,b))-Math.min(r,Math.min(g,b));total++;if(g>=50&&g>=r+6&&g>=b+2)z.green++;if(lum>=42&&lum<=215&&sp<=75)rr++;else if(lum<=45&&sp<=55)ff++;}z.road=rr/(float)total;z.fog=ff/(float)total;return z;}
 private static int cont(Bitmap s,int px,int py,int dx,int dy,int cell,boolean relax){int good=0,miss=0;for(int i=1;i<=10;i++){int x=px+Math.round(dx*i*cell),y=py+Math.round(dy*i*cell);if(x<0||y<0||x>=s.getWidth()||y>=s.getHeight())break;if(road(s,x,y,cell,relax)){good++;miss=0;}else if(++miss>=3&&i>=4)break;}return good;}
 private static int wide(Bitmap s,int px,int py,int dx,int dy,int cell){int n=0;for(int i=2;i<=9;i++){int x=px+Math.round(dx*i*cell),y=py+Math.round(dy*i*cell);for(int side=-1;side<=1;side++)if(road(s,x+dy*side*cell,y-dx*side*cell,cell,false))n++;}return n;}
 private static boolean road(Bitmap s,int cx,int cy,int cell,boolean relax){int g=0,n=0;for(int y=Math.max(0,cy-cell);y<=Math.min(s.getHeight()-1,cy+cell);y++)for(int x=Math.max(0,cx-cell);x<=Math.min(s.getWidth()-1,cx+cell);x++){int c=s.getPixel(x,y),r=Color.red(c),gg=Color.green(c),b=Color.blue(c),lum=(299*r+587*gg+114*b)/1000,sp=Math.max(r,Math.max(gg,b))-Math.min(r,Math.min(gg,b));if((lum>=42&&lum<=215&&sp<=75)||(relax&&lum>=35&&lum<=225&&sp<=90))g++;n++;}return g/(float)n>=(relax?.12f:.14f);}
 private static int[] findPlayer(Bitmap s,int w,int h){boolean[] m=new boolean[w*h],v=new boolean[w*h];int greenPixels=0;for(int y=1;y<h-1;y++)for(int x=1;x<w-1;x++){int c=s.getPixel(x,y),r=Color.red(c),g=Color.green(c),b=Color.blue(c);m[y*w+x]=g>=50&&g>=r+6&&g>=b+2;if(m[y*w+x])greenPixels++;}int bx=-1,by=-1,best=-1;for(int y=1;y<h-1;y++)for(int x=1;x<w-1;x++)if(m[y*w+x]&&!v[y*w+x]){ArrayDeque<Integer>q=new ArrayDeque<>();q.add(y*w+x);v[y*w+x]=true;int n=0,sx=0,sy=0,minx=x,maxx=x,miny=y,maxy=y;while(!q.isEmpty()){int id=q.removeFirst(),cx=id%w,cy=id/w;n++;sx+=cx;sy+=cy;minx=Math.min(minx,cx);maxx=Math.max(maxx,cx);miny=Math.min(miny,cy);maxy=Math.max(maxy,cy);for(int k=0;k<4;k++){int nx=cx+(k==0?1:k==1?-1:0),ny=cy+(k==2?1:k==3?-1:0);if(nx<1||ny<1||nx>=w-1||ny>=h-1)continue;int ni=ny*w+nx;if(m[ni]&&!v[ni]){v[ni]=true;q.addLast(ni);}}}int area=(maxx-minx+1)*(maxy-miny+1);if(n<5||area>5000)continue;int score=n*3-Math.abs((maxx-minx)-(maxy-miny))*2;if(score>best){best=score;bx=sx/n;by=sy/n;}}return new int[]{bx,by,greenPixels};}
 private static String pct(float x){return String.format(java.util.Locale.US,"%.1f%%",x*100);}
 private static String name(int x,int y){if(x>0&&y>0)return"↘";if(x>0&&y<0)return"↗";if(x<0&&y>0)return"↙";if(x<0&&y<0)return"↖";if(x>0)return"→";if(x<0)return"←";if(y>0)return"↓";return"↑";}
}
